### ISSUE TITLE
Found a little typo in your docs

### ISSUE THREAD

**Issue by mewcrazy** [rocky-linux/documentation#1064]
Hi guys,

I just wanted to let you know about a little typo in your docs on the page "Postfix Process Reporting" -> "Testing Mail First".

`cp /etc/**postifix**/main.cf /etc/postfix/main.cf.bak`

P.S. I'm new to Rocky Linux but till now I'm more than happy with it. Thanks!

Kind Regards,
Dennis Bitsch

**Comment by sspencerwire** [comment]
Hey, Thanks very much @mewcrazy ... I'll fix it right away.

**Comment by sspencerwire** [comment]
Just pushed and merged the change. It will take a little bit to see it in the docs, but not too long. Thank you again for this catch!

**Comment by mewcrazy** [comment]
Youre welcome. Great Response time!

sspencerwire ***@***.***> schrieb am Mo., 6. Feb. 2023, 21:57:
