### ISSUE TITLE
Kernel guide should have warnings to users

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/documentation#1082]
The kernel building guide should be noting to users that building and maintaining their own kernel is unsupported and provide warnings to users who wish to build them. Our wiki actually states the following:

```
Kernel rebuilds are not recommended nor supported for Rocky Linux. Before building a custom kernel or even considering it, ask yourself the following questions:

* Is the functionality you need available by installing a kernel module from [elrepo](https://elrepo.org)?
* Is the functionality you need available as a separate module from the kernel itself?
* Are you willing to maintain your own security posture?
* **Are you sure**? Rocky Linux and most other EL derivatives were designed to function as a complete environment. Replacing critical components can affect how the system acts.
* **Are you ABSOLUTELY sure**? 99.9% of the users no longer need to build their own kernel. You may simple need a kernel module/driver, in which case, you can use [elrepo](https://elrepo.org) or build your own kernel module (kmod/dkms)
* **Are you sure you don't just want a newer kernel version**? Newer kernels can be found at [elrepo](https://elrepo.org)

As a final warning, you if you break the kernel, you are on the hook for your system. Rocky Linux volunteers or developers are unable to assist you with these issues.
```

While it is a nice-to-have guide for users who want to build their own kernel or are learning, similar warnings should be given on the kernel building guide.

**Comment by sspencerwire** [comment]
@nazunalika I'm on the road this week, but should be home by Thursday and will tweak this document then if it hasn't already been handled. Thanks!

**Comment by sspencerwire** [comment]
![kernel_build_warning](https://user-images.githubusercontent.com/4265212/222277335-bf9e1ed5-c560-4ef0-afb2-5b2657f051d3.png)

**Comment by sspencerwire** [comment]
![kernel_build_warning](https://user-images.githubusercontent.com/4265212/222277712-bbd84551-ea25-4670-b811-65a539e02fe3.png)
