### ISSUE TITLE
Update NvChad docs

### ISSUE THREAD

**Issue by siduck** [rocky-linux/documentation#1095]
Hi there! author of NvChad here. v2.0 has recently released https://nvchad.com/news and it uses lazy.nvim instead of packer.nvim for package manager. There are few breaking changes ( mostly related to package manager ) but the config has gotten easier. 

old syntax is depreceated ( people can still use it tho! )

**Comment by sspencerwire** [comment]
Hey @siduck Thanks very much for the heads-up. As it turns out, the author of the Rocky Linux documentation for NvChad is very much aware of the changes and has already self-tested the new features. He will be working on updating our documentation as time allows. Thank you again!

**Comment by ambaradan** [comment]
Hi, @sspencerwire and @siduck I have updated the _install_nvchad_ and _builtin_plugins_ pages to reflect the changes in version 2.0. I think they are fine but a check never hurts.
