### ISSUE TITLE
Docker installation instructions say to use Docker's CentOS repository

### ISSUE THREAD

**Issue by Ghepardo** [rocky-linux/documentation#1104]
The page https://docs.rockylinux.org/gemstones/docker/ says to use Docker's CentOS repository.  This does not seem right: Rocky does not track CentOS, rather RHEL.  However, I see that Docker's RHEL repository covers only the IBM S390 architecture - https://docs.docker.com/engine/install/rhel/.  The latter page suggests trying the CentOS repository for RHEL on x86_64.  

To prevent everyone else to reads https://docs.rockylinux.org/gemstones/docker/ being confused and having to perform this same research, it would be useful if that page contained a little explanation of why Docker's CentOS repository was specified.

**Comment by sspencerwire** [comment]
Thank you @Ghepardo. I'm going to request @wsoyinka to review your suggestion and see if he will do the rewrite, as he is the author of this document. Thank you again!

**Comment by wsoyinka** [comment]
Hi @Ghepardo  :

Thank you for pointing this out. 

Unfortunately , Docker does not yet have official repos for Rocky Linux that we are aware of :-(.  Once they do [and we become aware], we'll update our documentation :-).
We've tested the current instructions using the available CentOS repo and they work perfectly. 

And yes, we can add a little extra note in the docs to clarify this reasoning. 

Cheers.

**Comment by lumarel** [comment]
@wsoyinka I'm pretty sure they mean to change the link here: https://github.com/rocky-linux/documentation/blob/main/docs/gemstones/docker.md#add-the-docker-repository
from `https://download.docker.com/linux/centos/docker-ce.repo` to `https://download.docker.com/linux/rhel/docker-ce.repo`, as Rocky tracks RHEL not CentOS (Stream).

If you look at the OS requirements, they say:
CentOS: https://docs.docker.com/engine/install/centos/
To install Docker Engine, you need a maintained version of one of the following CentOS versions:
- CentOS 7
- CentOS 8 (stream)
- CentOS 9 (stream)

RHEL: https://docs.docker.com/engine/install/rhel/
To install Docker Engine, you need a maintained version of RHEL 7, RHEL 8 or RHEL 9 on s390x (IBM Z). Archived versions aren’t supported or tested.
The overlay2 storage driver is recommended.
