### ISSUE TITLE
Failed to install devtools on Rocky Linux 9

### ISSUE THREAD

**Issue by murphytsai** [rocky-linux/documentation#1115]
I follow instructions to install devtools on Rocky Linux 9 but get the following error message:

$ sudo make install
sudo dnf config-manager --set-enabled powertools
Error: No matching repo to modify: powertools.
make: *** [Makefile:12: .system] Error 1

I'm newbie of RL .

**Comment by wsoyinka** [comment]
Hi @murphytsai :

Sorry to hear this :-(.  Which instructions or documentation are you following ?  Can you please share the URL if it is on the official Rocky Linux documentation site located here https://docs.rockylinux.org  ? 

For Rocky Linux 9 , the correct command to should be:

`dnf config-manager --set-enabled crb`


Cheers and please let us know if that works for you.

**Comment by murphytsai** [comment]
> 

I refer to the link : https://docs.rockylinux.org/guides/package_management/developer_start2/#2-install-rocky-devtools

btw, the commands you suggest has same issue.

**Comment by sspencerwire** [comment]
@wsoyinka Given the warning at the top of the page referenced by @murphytsai I think this document **needs** to be archived, or at minimum removed from view and TOC. Suggestions?

**Comment by wsoyinka** [comment]
@sspencerwire  - i agree with you.  

I just checked and the issue was in the Makefile itself and the tool/approach is likely deprecated.  
Let's archive the guide. 

Thank you @murphytsai , @sspencerwire :-)

**Comment by sspencerwire** [comment]
I've archived the document and will now close this issue.  Thanks all!
