### ISSUE TITLE
Translate docs/index.md into Ukrainian

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1265]
1. **_english reviewer:_** Review the base **english** article (punctuation, vocabulary, ...):
    https://docs.rockylinux.org/en/
    https://github.com/rocky-linux/documentation/edit/main/docs/index.md
2. **_translator:_** Propose **ukrainian** translations with Crowdin:
    https://crowdin.com/translate/rockydocs/523/en-uk
3. **_ukrainian reviewer (crowdin):_** Review the **ukrainian** translations in crowdin (downvote or delete wrong translations, upvote good translations, ...)
4. **_proofreader:_** Approve the **ukrainian** translations with Crowdin
5. **_external ukrainian reviewer:_** Review the final result in **ukrainian**:
    https://docs.rockylinux.org/uk/

**Comment by SergeCroise** [comment]
@gannazhyrnova,
please check this issue

**Comment by gannazhyrnova** [comment]
@alemorvan or @sspencerwire please delete autotranslation from here.
@SergeCroise I will back to this file later.
