### ISSUE TITLE
Add Afrikaans to the list of languages for Rocky

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1280]
Add Afrikaans (af?) to the list of languages for Rocky Docs.
See:
https://en.wikipedia.org/wiki/Afrikaans#Etymology
https://fr.wikipedia.org/wiki/Afrikaans
and
https://github.com/rocky-linux/documentation/blob/main/crowdin.yml

**Comment by SergeCroise** [comment]
Hello @sspencerwire and @alemorvan ,
If you agree,@Pieter and myself would like to add 
this language to Rocky Docs.

**Comment by SergeCroise** [comment]
Hello @sspencerwire, @alemorvan  and @willlempieterd
see also 
https://github.com/rocky-linux/rockylinux.org/pull/537

**Comment by SergeCroise** [comment]
https://github.com/rocky-linux/rockylinux.org/pull/538/files
https://github.com/rocky-linux/docs.rockylinux.org/pull/55/files
https://github.com/rocky-linux/documentation/pull/1300/files

**Comment by SergeCroise** [comment]
Good starting points to begin with the translations will be:
https://docs.rockylinux.org/guides/contribute/rockydocs_formatting/
https://crowdin.com/translate/rockydocs/310/en-af?filter=basic&value=5

**Comment by alemorvan** [comment]
- [ ] Add exception to *.af.md to the crowdin source
- [ ] Add af language to crowdin ui
- [ ] Give peters rights to af as translator and proofreader
- [ ] Add af to mkdocs config

**Comment by alemorvan** [comment]
Everything is ok.
Please you can start translating.
