### ISSUE TITLE
Add Indonesian, Bahasa Indonesia, ISO 639-1 Code: id

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1303]
see:
https://crowdin.com/project/rockylinuxorg/id
https://en.wikipedia.org/wiki/Indonesian_language#History
https://fr.wikipedia.org/wiki/Indonésien#Différences_entre_indonésien_et_malais_de_Malaisie

**Comment by alemorvan** [comment]
Added in crowdin.
Thx.

**Comment by SergeCroise** [comment]
those links should work soon:
https://crowdin.com/translate/rockydocs/310/en-id?filter=basic&value=5
or
https://crowdin.com/translate/rockydocs/221/en-id?filter=basic&value=5
https://crowdin.com/translate/rockydocs/109/en-id?filter=basic&value=5
https://crowdin.com/translate/rockydocs/412/en-id?filter=basic&value=5

**Comment by SergeCroise** [comment]
id.md file already generated:
https://github.com/rocky-linux/documentation/blob/main/docs/index.id.md
but
https://docs.rockylinux.org/id/
waiting for 
https://github.com/rocky-linux/docs.rockylinux.org/pull/56
