### ISSUE TITLE
Add Czech, Čeština, ISO 639-1 Code: cs

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1304]
See:
https://crowdin.com/project/rockylinuxorg/cs
https://cs.wikipedia.org/wiki/Čeština
https://en.wikipedia.org/wiki/Czech_Americans#The_top_50_U.S._communities_with_the_highest_percentage_of_people_claiming_Czech_ancestry
https://fr.wikipedia.org/wiki/Langues_slaves#Classification

**Comment by alemorvan** [comment]
Added in crowdin.
Thx.

**Comment by SergeCroise** [comment]
https://crowdin.com/translate/rockydocs/310/en-cs?filter=basic&value=5
or
https://crowdin.com/translate/rockydocs/221/en-cs?filter=basic&value=5
https://crowdin.com/translate/rockydocs/109/en-cs?filter=basic&value=5
https://crowdin.com/translate/rockydocs/412/en-cs?filter=basic&value=5
