### ISSUE TITLE
indonesian translation show up while using english version of the books

### ISSUE THREAD

**Issue by Just-some-one** [rocky-linux/documentation#1345]
Hello

1) go to `https://docs.rockylinux.org/books/`
2) click on `System Administrator's Guide`
you will find `Belajar Linux Dengan Rocky ` which should be under the indonesian translation of the `Learning Linux With Rocky `

another issue related to it
1) click on `Belajar Linux Dengan Rocky ` link 
2) click on `Learning Linux With Rocky ` link
it will give you page not found `404 - Not found `

thanks for your great work and have a nice day :)

**Comment by sspencerwire** [comment]
Thank you @Just-some-one Our web team has a PR that needs to be merged to enable the language properly, which should then exclude it from the English language listing. I appreciate the heads-up!

**Comment by Just-some-one** [comment]
thanks for you @sspencerwire  and the whole team :)

**Comment by SergeCroise** [comment]
This PR: https://github.com/rocky-linux/docs.rockylinux.org/pull/56
solved this issue,
see also:
https://docs.rockylinux.org/id/
https://docs.rockylinux.org/id/books/admin_guide/00-toc/
https://docs.rockylinux.org/id/release_notes/
https://docs.rockylinux.org/id/books/disa_stig/disa_stig_part1/
https://docs.rockylinux.org/id/books/disa_stig/disa_stig_part2/

**Comment by sspencerwire** [comment]
@Just-some-one This is now resolved. Thank you again!
