### ISSUE TITLE
Kernel build instructions web page formatting issue

### ISSUE THREAD

**Issue by hwoithe** [rocky-linux/documentation#1365]
The kernel build instructions web page contains a slight formatting issue.
https://docs.rockylinux.org/guides/custom-linux-kernel/

![firefox-screenshot](https://github.com/rocky-linux/documentation/assets/1168868/8894edd1-8863-43d0-9e6b-bdf9f509e4e1)

Is it possible that the extra whitespace is the cause of this?
https://github.com/rocky-linux/documentation/blob/f0a2ada450c025314dc62ba4a336681bd28fbe7d/docs/guides/custom-linux-kernel.md?plain=1#L78

**Comment by sspencerwire** [comment]
Thanks @hwoithe I'll take a look at this now and let you know what I see.

**Comment by sspencerwire** [comment]
@hwoithe This should be fixed. There was an extra space before the tripple ticks on that line that was causing the formatting issue (and the display of the ticks).... let me know if your experience is different and thank you very much for the heads-up!
