### ISSUE TITLE
[type:bug] Link to installation guide is broken

### ISSUE THREAD

**Issue by DejfCold** [rocky-linux/documentation#146]
On the URL https://docs.rockylinux.org/release_notes/8.4/#anaconda-help-button-not-functioning-20 (`Anaconda "Help" Button not functioning (#20)`) there's a link to `installation walk-through` which doesn't work. The link redirects to https://docs.rockylinux.org/release_notes/guides/rocky-8-installation/ which is not found.

**Comment by wsoyinka** [comment]
Thank you for catching this.   Now fixed.
