### ISSUE TITLE
Can't be update and can be broken

### ISSUE THREAD

**Issue by rober7o0** [rocky-linux/documentation#1590]
Hi, i just getting many error when i try to update by dnf update, but if i update by software update the system come broken.
I can't use console and kate and after of reeboot i cant load the desktop

**Comment by sspencerwire** [comment]
Hello @rober7o0 . I'm sorry you are having trouble, but this isn't the place to report problems related to your system. Try creating an account on our [forums](https://forums.rockylinux.org/) and creating your issue there. You'll need to provide more detail about your system to get much help. If you have an account in our [Mattermost](https://chat.rockylinux.org/) try the General channel there for help with your issue. If you don't have an account, you can easily create one.
