### ISSUE TITLE
Podman Local Development (docs.rockylinux.org) Guide 

### ISSUE THREAD

**Issue by j0eybrinkman** [rocky-linux/documentation#1714]
I followed this guide step-by-step and it does not work for my system.

Tested on: 
OS-release = Rocky Linux 9.3
Python version = 3.9
Podman version = 4.6.1

Guide: https://docs.rockylinux.org/guides/contribute/localdocs/rockydocs_webdev_v2/

Errors during final step, running 'docker-compose up':
rockydocs-mkdocs-1  | error: patch failed: requirements.txt:1
rockydocs-mkdocs-1  | error: requirements.txt: patch does not apply
rockydocs-mkdocs-1  | error: patch failed: mkdocs.yml:58
rockydocs-mkdocs-1  | error: mkdocs.yml: patch does not apply
rockydocs-mkdocs-1 exited with code 1

**Comment by sspencerwire** [comment]
@j0eybrinkman I'm sorry that this procedure isn't working for you. Let me see if I can duplicate your issue. Thank you!

**Comment by sspencerwire** [comment]
@j0eybrinkman I was able to get this to work in 9.3 w/o an issue, however there does appear to be a problem with the `docker-compose up` command, as for me, I had to run it with `sudo` or I got permissions errors. [disclaimer: I don't use this particular local docs method, so I did this in a container just to test the procedure.]  A couple of questions: 
1. Did you start by verifying that the prerequisites were met? For me, I just went to that section and installed them all, even if they already existed, just to be sure.
2. If you run `pwd` just prior to running the `docker-compose up` command, what does it show?

**Comment by sspencerwire** [comment]
@wale Can you perhaps lend a hand here with @j0eybrinkman and this procedure?  I've asked a couple of questions above.

**Comment by j0eybrinkman** [comment]
Ran through the steps again but I get the same errors. I'm not sure what I am doing wrong. 

sudo dnf -y install podman podman-docker git

sudo systemctl enable --now  podman.socket

sudo curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose

sudo chmod 755 /usr/local/bin/docker-compose

sudo chmod 666 /var/run/docker.sock

git clone https://github.com/rocky-linux/documentation.git

git clone https://github.com/rocky-linux/docs.rockylinux.org.git

systemctl  enable --now podman.socket

curl -SL https://raw.githubusercontent.com/rocky-linux/documentation-test/main/docs/labs/docker-compose-rockydocs.yml -o docker-compose.yml

docker-compose  up

---------------------------------------------------

pwd = /home/me/projects/rockydocs

---------------------------------------------------

I had to run sudo to output docker-compose to /usr/local/bin but did not need to use it to run docker-compose.

**Comment by wale** [comment]
> @wale Can you perhaps lend a hand here with @j0eybrinkman and this procedure? I've asked a couple of questions above.

I don't think I can help, because [I have no relation to the Rocky Linux project](<https://github.com/rocky-linux/documentation/pull/1236#issuecomment-1577915893>). You must have me confused for someone else.

**Comment by wsoyinka** [comment]
@j0eybrinkman   @sspencerwire  -  New updated docker image has been updated to the registry.   Please try again.  

(p.s. I need to look further into the docker compose approach.   Launching or using with compose is broken)

**Comment by sspencerwire** [comment]
@j0eybrinkman Is this issue resolved?

**Comment by j0eybrinkman** [comment]
@sspencerwire I will test tonight and record going through steps! Will update soon

**Comment by j0eybrinkman** [comment]
![Screenshot from 2024-05-06 23-20-37](https://github.com/rocky-linux/documentation/assets/122839775/f843ebb9-496a-4d52-952c-3b0ebcebabb1)

**Comment by j0eybrinkman** [comment]
> @j0eybrinkman @sspencerwire - New updated docker image has been updated to the registry. Please try again.
> 
> (p.s. I need to look further into the docker compose approach. Launching or using with compose is broken)

How do you run it without using docker-compose? When I try using docker-compose up it fails with errors in above image.

**Comment by j0eybrinkman** [comment]
I'm really not sure what I'm missing. I follow the document exactly and it fails to work. Admittedly I am a complete novice to containers. Here's a document of my struggles - https://youtu.be/eegghR77Og4. Sorry to have this issue open for so long. I'm going to read through all the container guides and maybe that will get me up to speed...
