### ISSUE TITLE
Add Turkish, Türkçe, ISO 639-1 Code: tr

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1747]
- update crowdin.yml (done)
- grant access to tr in Crowdin (translator and proofreader)
- update mkdocs (done)
- translate e.g.: https://crowdin.com/editor/rockydocs/672/en-tr

see also https://crowdin.com/project/rockydocs

**Comment by SergeCroise** [comment]
Pull requests:
https://github.com/rocky-linux/documentation/pull/1748
https://github.com/rocky-linux/docs.rockylinux.org/pull/66

**Comment by SergeCroise** [comment]
Links to translate (examples):
https://crowdin.com/editor/rockydocs/523/en-tr
https://crowdin.com/editor/rockydocs/672/en-tr
https://crowdin.com/editor/rockydocs/668/en-tr

**Comment by sspencerwire** [comment]
@SergeCroise Can this issue be closed, or does more need to be done?

**Comment by SergeCroise** [comment]
> @SergeCroise Can this issue be closed, or does more need to be done?

can be closed.
