### ISSUE TITLE
Add Spanish, Argentina, ISO 639-1 Code: es-AR

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1762]
- update crowdin.yml (todo)
- grant access to es-AR in Crowdin (translator and proofreader)
- update mkdocs.yml (todo)
- translate e.g.: https://crowdin.com/editor/rockydocs/672/en-esar

see also https://crowdin.com/project/rockydocs

**Comment by sspencerwire** [comment]
@SergeCroise I'm going to close this one too, since it isn't possible in `material-mkdocs`... thank you!
