### ISSUE TITLE
fr: help needed, french items to be reviewed

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1786]
Help needed ! 
Nous cherchons des volontaires pour passer en revue les articles suivants :
**Books:**
https://crowdin.com/editor/rockydocs/15/en-fr (environ 300 mots, 25 phrases)
https://crowdin.com/editor/rockydocs/545/en-fr (environ 1000 phrases)
**Gemstones:**
https://crowdin.com/editor/rockydocs/597/en-fr (environ 300 mots, 22 phrases)
**Guides:**
https://crowdin.com/editor/rockydocs/306/en-fr (environ 400 phrases)
**Labs:**
https://crowdin.com/editor/rockydocs/277/en-fr (environ 1234 mots, 100 phrases)
**Releases notes:**
https://crowdin.com/editor/rockydocs/412/en-fr (environ 567 mots, 49 phrases)
**Nouveaux articles:**
https://crowdin.com/editor/rockydocs/523/en-fr (environ 678 mots, 55 phrases)

Si vous trouvez des erreurs, n'hésitez pas à nous contacter dans mattermost :
https://chat.rockylinux.org/rocky-linux/channels/l10n

**Comment by SergeCroise** [comment]
Hello Antoine @alemorvan ,
please tell me welcher Artikel should be reviewed first ?

**Comment by alemorvan** [comment]
- [ ] Commandes pour utilisateurs Linux: https://crowdin.com/editor/rockydocs/545/en-fr 
- [ ] Apprendre Linux avec Rocky : https://crowdin.com/editor/rockydocs/15/en-fr
- [ ] Gemstones : https://crowdin.com/editor/rockydocs/597/en-fr
- [ ] Compiler et installer des noyaux Linux personnalisés : https://crowdin.com/editor/rockydocs/306/en-fr
