### ISSUE TITLE
L10n,I18n: write an article about l10n, i18n, and why it could be useful to create basic items in any language

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1829]
- write a new article about l10n and i18n 
- start a discussion e.g., in Mattermost 
- brainstorming: discuss ideas about basic items in any language
- translate the basic items into supported languages 
   (e.g., en-US, en-GB, es-AR, es-CO, es-DO, pt-PT, pt-BR, uk, af, de, es, id, it, nl, ...)
- sort the languages in the 文A combobox, 
   the same order than https://crowdin.com/project/rockydocs (sort by:completed first)
- TM, MT, crowdin, etc.
- wiki: https://github.com/rocky-linux/documentation/wiki

see also:
https://chat.rockylinux.org/rocky-linux/channels/l10n
https://crowdin.com/project/rockydocs/ (the languages supported by rockydocs, for now)
https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/ (the languages supported by MkDocs)
https://developer.crowdin.com/language-codes/ (the languages supported by crowdin)

**Comment by sspencerwire** [comment]
@SergeCroise What is the status of this issue?  Has this been discussed in Mattermost as you originally indicated?  Does it still need to happen in your opinion? If the discussion needs to happen, then you should go ahead and start that conversation. Just going through the currently open issues and trying to see which ones need attention, or should be closed.  Thank you!

**Comment by SergeCroise** [comment]
I suggest to close this issue, not needed anymore.
