### ISSUE TITLE
RFE: Add how to check x86-64-v2 on all Rocky Linux 9 release notes pages

### ISSUE THREAD

**Issue by nazunalika** [rocky-linux/documentation#1843]
A common question that comes up is how to determine if a CPU supports x86-64-v2. This is common in the form of a bug report or on the forums, where screenshots show a kernel panic that hints to the lack of these extensions.

There could possibly be a section on each Rocky Linux 9.X page that mentions how to check for these extensions, by mentioning to boot up Rocky Linux 8 or Fedora, and run something similar to this:

```
$ /lib64/ld-linux-x86-64.so.2 --help | grep x86-64
Usage: /lib64/ld-linux-x86-64.so.2 [OPTION]... EXECUTABLE-FILE [ARGS-FOR-PROGRAM...]
This program interpreter self-identifies as: /lib64/ld-linux-x86-64.so.2
  x86-64-v4
  x86-64-v3
  x86-64-v2 (supported, searched)
```

The example above shows that x86-64-v2 is supported on this host's CPU, but not v3 or higher.

**Comment by sspencerwire** [comment]
@nazunalika This should be handled now with [this document](https://docs.rockylinux.org/gemstones/test_cpu_compat/) as well as links to that procedure in each RL 9.x release notes page. Can we close this issue?

**Comment by nazunalika** [comment]
This looks good, thank you for the quick turn around!
