### ISSUE TITLE
Add Persian (Farsi), ISO 639-1 Code: fa

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1858]
Farsi is supported by MkDocs:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/

See also:
https://crowdin.com/project/rockylinuxorg
and
https://crowdin.com/project/rockylinuxorg/activity-stream

**Comment by sspencerwire** [comment]
@SergeCroise Again, I'm not inclined to add languages unless we have specific translators requesting such. Thanks for all you do!
