### ISSUE TITLE
Add Hindi, Sanskrit and Telugu, ISO 639-1 Codes: hi, sa, te

### ISSUE THREAD

**Issue by SergeCroise** [rocky-linux/documentation#1871]
**Prerequisites:**
Hindi (हिन्दी),  Sanskrit (संस्कृतम्) and Telugu (తెలుగు) are supported by MkDocs:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/

**Todos:**
- update crowdin.yml (todo)
- grant access to hi, sa, te, (es) in Crowdin (translator and proofreader)
- update mkdocs.yml (todo)
- translate e.g.: https://crowdin.com/editor/rockydocs/523/en-es
   or https://crowdin.com/editor/rockydocs/15/en-es

**See also:**
https://crowdin.com/project/rockydocs/hi
https://crowdin.com/project/rockydocs/sa
https://crowdin.com/project/rockydocs/te
and
https://crowdin.com/project/rockydocs/activity-stream
https://crowdin.com/project/rockylinuxorg/hi

**What the heck...**
https://en.wikipedia.org/wiki/Languages_of_India

**Comment by sspencerwire** [comment]
@SergeCroise I'm not inclined to add new languages to the engine without specific translators waiting in the wings to do the translation. I think that is @wsoyinka opinion as well. The overhead of the additional languages without need creates problems. In addition, with the streamlining of web's involvement, we seem to be able to add languages very quickly when needed. Thanks for all that you do!
