### ISSUE TITLE
What exactly does "follow" mean in the GitHub context?

### ISSUE THREAD

**Issue by reppep** [rocky-linux/documentation#2028]
I haven't used GitHub recently, but I'm confused by "Login to GitHub and follow the official [Rocky Linux documentation repository](https://github.com/rocky-linux/documentation)." on <https://github.com/rocky-linux/documentation>. I don't see a 'follow' action in GitHub's UI. Do you mean 'Watch', 'Star', or something else?

**Comment by sspencerwire** [comment]
@reppep Essentially, that just means to "follow that site"... you could do this with your web browser favorites tab, bookmark, or some other means. If you feel this could be worded more clearly, I'm open to suggestions!  Thank you!

**Comment by reppep** [comment]
I thought ‘follow’ referred to some kind of GitHub subscription or Watch setting. How about “keep an eye on”?

Chris

**Comment by sspencerwire** [comment]
> I thought ‘follow’ referred to some kind of GitHub subscription or Watch setting. How about “keep an eye on”? Chris
> […](#)
Because of other languages (translations), I think that might qualify as slang. but we could just change it to "watch"

**Comment by reppep** [comment]
That’s a good point, but I think Watch is a specific GitHub verb. I didn’t see a way to Watch an entire project, unfortunately.

Chris

**Comment by sspencerwire** [comment]
Let me see if I can think of a way to reword this so it makes sense.  Thank you!

**Comment by Grammaresque** [comment]
Hi, I wrote that. Really all I meant by it was "find" Rocky Linux by clicking the link in that same sentence.

**Comment by Grammaresque** [comment]
Personally, as a not-extensive user of GH, when I want to follow a repo I fork it to my own directory.

**Comment by sspencerwire** [comment]
We may want to revisit this at some point and perhaps reword a few things. For now, I think we will close the issue. Thanks all!
