### ISSUE TITLE
GitHub formatting vs. style guide

### ISSUE THREAD

**Issue by reppep** [rocky-linux/documentation#2031]
https://github.com/rocky-linux/documentation includes a bullet list with this item:

they are two space indented and start with a "-" as shown here

Unfortunately it's bulleted, and doesn't start with two spaces or a hyphen. "as shown here" should be removed if the primary way people see it won't show space-space-dash.

**Comment by sspencerwire** [comment]
@reppep Good suggestion! I think a fenced text block should do the trick for that section. I've pushed the change and will be merging it shortly. Thank you!

**Comment by sspencerwire** [comment]
@reppep That PR is now merged. If you think that solves the issue, we can go ahead and close this.

**Comment by reppep** [comment]
Looks good, thanks!
