### ISSUE TITLE
Typo in Lab: 3 Common System Utilities under Exercise 14 number 6

### ISSUE THREAD

**Issue by Rody10** [rocky-linux/documentation#2042]
There is a typo in Lab: 3 Common System Utilities under Exercise 14, number 6. There is a section that says "Use the find command to find all the find all the files ..." instead of "Use the find command to find all the ...".

**Comment by wsoyinka** [comment]
This is now fixed.  Thank you @Rody10  :-)

**Comment by sspencerwire** [comment]
Since this is fixed, I'm going to go ahead and close this issue. Thanks @Rody10 !
