### ISSUE TITLE
`podman generate systemd` is deprecated

### ISSUE THREAD

**Issue by ChrSteinert** [rocky-linux/documentation#2093]
The documentation over at https://docs.rockylinux.org/gemstones/containers/podman/ suggests using `podman generate systemd`, which is deprecated. The [Podman documentation](https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html) suggests using quadlets going forward.

I think it would be great to either
- have the documentation have a hint about the deprecation, or
- have an additional example for using quadlet, or
- switch to quadlet usage completely.

If any of this would be of interest to the project, I would be willing to help/write it.

**Comment by sspencerwire** [comment]
Greetings @ChrSteinert and thank you for your suggestion! Yes, please go ahead and do a pull request with your suggested modifications. I'd add an admonition (probably a warning type) near the section about `podman generate systemd` and then put in the example for using quadlet. I think that leaving the deprecated code in place at this point is preferable to just re-writing it entirely for quadlet. But write it up in a way that lets the reader know that the former is going away and that quadlet is the way going forward.

**Comment by cyqsimon** [comment]
There is the excellent tool https://github.com/containers/podlet which can aid the transition FYI.

I've been using quadlets in small-scale prod since I saw [this RH article](https://www.redhat.com/sysadmin/quadlet-podman). So far things have been flawless. Much better than juggling `.service` files.

**Comment by sspencerwire** [comment]
> There is the excellent tool https://github.com/containers/podlet which can aid the transition FYI. Should probably include it in the documentation. Also, there's a similar section in the associated full document here: https://docs.rockylinux.org/guides/containers/podman_guide/, which should be updated as well.
> 
> I've been using quadlets in small-scale prod since I saw [this RH article](https://www.redhat.com/sysadmin/quadlet-podman). So far things have been flawless. Much better than juggling `.service` files.

@cyqsimon I welcome their inclusion! As I replied to @ChrSteinert we would love you to go ahead and write up any changes you think are required and submit them. It's better that these things are written by the folks who use them and can properly articulate them in a document. I'm not currently a Docker or Podman user. There are others on the team who are, but again it all boils down to who has the experience with the tools and is willing to write up the doc changes. We welcome those changes!!

**Comment by neelchauhan** [comment]
There's still something to keep in mind: The Rocky Linux Podman version might be older than the one using quadlets. This isn't Fedora, even if we are based on it (via RHEL).

It's similar to how EL 6 had Apache 2.2 even when 2.4 came out 2.5 years before EL7, but I was a Debian and later FreeBSD user during those years.

**Comment by cyqsimon** [comment]
@neelchauhan Quadlets were available since Podman 4.4. Both Rock 8&9 are on Podman 4.9.4 so we're good to go.

**Comment by ChrSteinert** [comment]
Could you please have a look at my first draft and let me know, if that is going into the right direction:

https://github.com/ChrSteinert/documentation/blob/main/docs/gemstones/containers/podman.md 

Thanks!

**Comment by cyqsimon** [comment]
> Could you please have a look at my first draft and let me know, if that is going into the right direction:
> 
> https://github.com/ChrSteinert/documentation/blob/main/docs/gemstones/containers/podman.md
> 
> Thanks!

Great work! I'm happy to help review it. I think it's most convenient if you can put in a PR and people can work off that.

**Comment by sspencerwire** [comment]
Closing this now that we have content updated. Thanks again @ChrSteinert
