### ISSUE TITLE
Readme links to incompatible style guide

### ISSUE THREAD

**Issue by ChrSteinert** [rocky-linux/documentation#2106]
The repos readme links unter _Technical Requirements_ → _ Markdown_ the a _basic writing and formatting guide_ (https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).
This guide contains syntax for [alerts](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts), that are not compatible with the rocky linux docs (see #2103, where I introduced issues because of that).

**Comment by sspencerwire** [comment]
Thanks very much @ChrSteinert ! This should be fixed with PR #2110 that I'll merge shortly.

**Comment by sspencerwire** [comment]
Just merged 2110, I'll close this issue, but you are welcome to reopen or open a new one if there is something else that isn't quite right.
