### ISSUE TITLE
Still have errors WRT Issue 2115 - Error "Failed to run 'config for nvim-lint" after running steps @ https://docs.rockylinux.org/books/nvchad/vale_nvchad/ #2115

### ISSUE THREAD

**Issue by drfooser2** [rocky-linux/documentation#2120]
After applying the recommended change, I am getting a different error than before.

I'm sorry to be this much trouble but I really want to use NvChad as my python/powershell/markdown IDE, and also to advocate for it as a great tool.

So just to be clear, this is what I have done., and the error I get now.
1. I successfully installed nvim and NvChad per https://docs.rockylinux.org/books/nvchad/install_nvchad/
2. executed the instructions @ https://docs.rockylinux.org/books/nvchad/vale_nvchad/#installation-of-nvim-lint.

![NvChad_nvim_lint_Error2](https://github.com/rocky-linux/documentation/assets/162844634/a6f57e23-8e92-42b7-953f-fec4f15afbca)

**Comment by ambaradan** [comment]
Don't put it in *init.lua*, as it is configured it should be in a separate file, the function:

```lua
return {
}
```


is for returning a table to put in the configuration.
There is no need to write everything into *init.lua* all correctly configured *.lua* files in the `plugins` folder are automatically loaded.

**Comment by ambaradan** [comment]
From the Guide

> To install the nvim-lint plugin, simply create a nvim-lint.lua file in the lua/plugins folder; when the Neovim instance is next started, this will be integrated into the configuration.

**Comment by ambaradan** [comment]
For *init.lua*

```lua
{
  "mfussenegger/nvim-lint",
  enabled = true,
  event = "VeryLazy",
  config = function()
    require("lint").linters_by_ft = {
    markdown = { "markdownlint", "vale" },
    }
  vim.api.nvim_create_autocmd({ "BufWritePost" }, {
  callback = function()
  require("lint").try_lint()
  end,
  })
  end,
},

**Comment by drfooser2** [comment]
I have news. First- Thiank you for your support!

I installed from fresh - deleting these:
~/.config/nvim
~/.local/share/nvim~/.cache/nvim

but I did review your docs again after your edits and found I had named the file incorrectly:
I named it plugins/nvim.lint.lua
It needs to be plugins/nvim-lint.lua (and your docs reflect this) so my bad there.
Once I corrected the file name the rest went well.

But I'm still wanting with respect to python linting.
The markdown linter is working as advertised (Yes! Very cool!)
But I am trying to get flake8 to work as a python linter, and it's not working.

Mason shows it installed.
[image.png]

and I have added flake8 to the plugins/nvim-lint.lua file, but it doesn't offer corrections in the editor like markdown does.

-----------
return {
{
"mfussenegger/nvim-lint",
enabled = true,
event = "VeryLazy",
config = function()
require("lint").linters_by_ft = {
markdown = { "markdownlint", "vale" },
yaml = { "yamllint" },
python = { "flake8" },
}

vim.api.nvim_create_autocmd({ "BufWritePost" }, {
callback = function()
require("lint").try_lint()
end,
})
end,
},
}

Paul

**Comment by ambaradan** [comment]
I'm glad you solved it, unfortunately I have no experience with python and wouldn't know how to help you. For any other needs I am available. The beauty of NvChad is precisely its ability to be modified at will (this actually comes from Neovim) and I'm sure you'll find some guidance on how to configure Python. Look for the combination "Neovim + lazy.nvim + Python," what you find can certainly be adapted to NvChad. Good luck

**Comment by drfooser2** [comment]
Thanks again for your support!

Paul

**Comment by ambaradan** [comment]
@drfooser2 Have you tried other formatters such as *black*?

https://github.com/psf/black

I am getting curious, maybe I will try to configure it for *python* language too!!!

**Comment by ambaradan** [comment]
If after configuring *flake8* open a python file in NvChad what is the result of the `LspInfo` command?

**Comment by ambaradan** [comment]
One more thing, the plugin is loaded in *lazy mode* and is activated by the `BufWritePost` event this means that when you open the file you haven't loaded the plugin yet, to activate it you have to save the file even if you haven't made any changes and at that time you have the linter active.

**Comment by ambaradan** [comment]
There seem to be faster alternatives, Ruff has two separate packages one LSP (ruff-lsp) and one for the linter (ruff).

https://pythonspeed.com/articles/pylint-flake8-ruff/

**Comment by drfooser2** [comment]
I have to say, your support for this issue is outstanding.
Thank you.

It's working!
The top box shows the a few linter warning.
The bottom box shows the output of LspInfo.

[image.png]

I think its working as designed!
Thanks again for your support.

Time to develop.
Paul

**Comment by ambaradan** [comment]
Great, so you have solved your configuration problems. I think it's time to close this issue, you should be able to do that too, I don't think you need an administrator for that.
Happy development
