### ISSUE TITLE
Joey Brinkman RSOD proposals

### ISSUE THREAD

**Issue by sspencerwire** [rocky-linux/documentation#2153]
Proposed Topics / Titles
      - GNOME Shell Extensions **Completed**
      - Running Windows games with Wine and Proton
      - Wireguard VPN setup and configuration
      - Hardware compatibility and driver installation for NVIDIA GPUs
      - Hardware compatibility and driver installation for Printers and Scanners
      - Using App Images and Maintaining a Secure System with SELinux
      - Best practices for managing SELinux in a workstation environment
      - `ksnip` tool **Completed** (up-voted as a good candidate for RSOD by @sspencerwire)
      - HP All-in-One Printer Installation and Setup **Completed**
      - Brother All-in-One Printer Installation and Setup **Completed**
      - Providing Secure Remote Support over LAN with x11vnc over SSH **Completed**

**Comment by sspencerwire** [comment]
@j0eybrinkman Add yourself to this issue and this is where we will discuss which documents we would like you to pursue.

**Comment by j0eybrinkman** [comment]
Hello, excited to contribute to some articles! Adding to the proposal list - for the Wireguard VPN setup, I'd like to offer a guide on x11vnc over wireguard as a remote support solution. For printing, I can do brother all-in-one.

**Comment by sspencerwire** [comment]
> Hello, excited to contribute to some articles! Adding to the proposal list - for the Wireguard VPN setup, I'd like to offer a guide on x11vnc over wireguard as a remote support solution. For printing, I can do brother all-in-one.

I think that would be great. Let's discuss the list with @wsoyinka. We should note that the "GNOME Shell Extensions" document is completed, and I'd like to propose that we accept that one as a good fit for RSOD.

**Comment by j0eybrinkman** [comment]
Proposed completed article - Annotating Screenshots with Ksnip

**Comment by j0eybrinkman** [comment]
Today I plan on working on the brother all-in-one printer article. I was wondering if creating an article for one of the system management tools from this issue https://github.com/rocky-linux/documentation/issues/2020#top would be a good fit for the tools folder the knsip article was placed in. I would like to cover the network panel Netwok Manager and command line equivalents like nmcli

**Comment by sspencerwire** [comment]
> Today I plan on working on the brother all-in-one printer article. I was wondering if creating an article for one of the system management tools from this issue [#2020 (comment)](https://github.com/rocky-linux/documentation/issues/2020#top) would be a good fit for the tools folder the knsip article was placed in. I would like to cover the network panel Netwok Manager and command line equivalents like nmcli

I think covering the Network Manager GUI portions and referring to already existing documents for `nmcli` would be best. I'm going to add `ksnip` to your proposed documents, mark it complete, and up-vote it with @wsoyinka

**Comment by sspencerwire** [comment]
> > Today I plan on working on the brother all-in-one printer article. I was wondering if creating an article for one of the system management tools from this issue [#2020 (comment)](https://github.com/rocky-linux/documentation/issues/2020#top) would be a good fit for the tools folder the knsip article was placed in. I would like to cover the network panel Netwok Manager and command line equivalents like nmcli
> 
> I think covering the Network Manager GUI portions and referring to already existing documents for `nmcli` would be best. I'm going to add `ksnip` to your proposed documents, mark it complete, and up-vote it with @wsoyinka

@j0eybrinkman Add these new proposed issues to the "Proposed topics/titles" above!

**Comment by j0eybrinkman** [comment]
@sspencerwire I am not sure how to edit your proposed titles or assign myself to the issue. I haven't been able to find the menu options to do so. I can quote a reply but I don't see edit or assign yourself to issue.

**Comment by sspencerwire** [comment]
> @sspencerwire I am not sure how to edit your proposed titles or assign myself to the issue. I haven't been able to find the menu options to do so. I can quote a reply but I don't see edit or assign yourself to issue.

That's fine, I can edit the proposed titles list for you if you just want to add them as comments here.

**Comment by sspencerwire** [comment]
@j0eybrinkman and @wsoyinka Let's discuss the remaining items in your list and decide whether they are a good fit for RSOD. I'm including @wsoyinka in this for his feedback:
* GNOME shell extensions: I'm up-voting this as valuable to the RSOD section.
* Running Windows games with Wine and Proton. While not technically a value to the enterprise, there is value to the Desktop home user. Thoughts?
* Wireguard VPN setup and configuration. In my opinion, this is a good fit for RSOD.
* Hardware compatibility and driver installation for NVIDIA GPUs
* Hardware compatibility and driver installation for Printers and Scanners
* Using App Images and Maintaining a Secure System with SELinux
(all of 3 of these are _probably_ a good fit for RSOD
* Best practices for managing SELinux in a workstation environment. To me, this is more of a general guide than one that fits within the desktop category. Thoughts?
* `ksnip` tool Completed (up-voted as a good candidate for RSOD by @sspencerwire)
* HP All-in-One Printer Installation and Setup Completed
* Brother All-in-One Printer Installation and Setup
Both HP and Brother printers are used extensively in the enterprise. (at least they were when I was working in the industry), so having these documents in the RSOD seem to be a good fit to me. 

I'll wait for @wsoyinka to chime in here, but if you have additional feedback @j0eybrinkman, feel free to quote and reply.

**Comment by wsoyinka** [comment]
I'd like to up-vote  the following proposed titles submitted by @j0eybrinkman :


1.           - GNOME Shell Extensions Completed
2.            - Running Windows games with Wine and Proton
3.       - Wireguard VPN setup and configuration
4.        - Hardware compatibility and driver installation for NVIDIA GPUs
5.        - Hardware compatibility and driver installation for Printers and Scanners
**6.        - Using App Images and Maintaining a Secure System with SELinux**
7.        - ksnip tool Completed (up-voted as a good candidate for RSOD by @sspencerwire)
8.        - HP All-in-One Printer Installation and Setup Completed
9.        - Brother All-in-One Printer Installation and Setup


#6  is not clear to me.  Feels like it should be 2 completely separate guides/docs.  i.e.  " Using App Images and Maintaining a Secure System with SELinux"

**Comment by sspencerwire** [comment]
> @j0eybrinkman Add yourself to this issue and this is where we will discuss which documents we would like you to pursue.

I was able to add you as an assignee to the issue.

**Comment by j0eybrinkman** [comment]
I have a few adjustments/clarifications to the proposals I'd like to run by you @sspencerwire @wsoyinka. The purpose I had in mind with Wireguard VPN setup and config, is setting up a low-cost and low-bandwidth remote support solution for Rocky 9 workstation. I have personal experience with this P2P remote support solution including its pros and cons compared to a more traditional centralized VPN such as OpenVPN. I also noticed there is already a guide for Tailscale VPN in the Security category. For this reason, I propose doing the following articles. 


Desktop Category:
- [X] GNOME Shell Extensions
- [X] HP All-in-One Printer Installation and Setup 
- [X] Brother All-in-One Printer Installation and Setup
- [X] ksnip
- [] Providing Secure Remote Support over LAN with x11vnc over SSH
- [] Providing Secure Remote Support over WAN with VPN and x11vnc 
- [] Hardware compatibility and driver installation for NVIDIA GPUs

Security Category:
- [] WireGuard VPN setup and configuration
- [] OpenVPN setup and configuration

As a side note, I've been taking videos of doing these processes with OBS and using Davinci Resolve to edit them down, but only today did I learn how to export a clip as a still frame. Now that I know how to do that as well as annotate screenshots with ksnip I plan on supplementing my guides with more screenshots and visuals as requested.

**Comment by wsoyinka** [comment]
@j0eybrinkman   - Trying to follow along.  But from your list are you proposing :

A) - doing everything in the list 
B) - Or only the things with check marks  (I see only 4 check marked items at my end) 


Unrelated -   your comment about video got me thinking about something that's been lurking on my mind for a while. i.e. Videos and Docs. Or videos/screencasts embedded in our docs.  If you want to go through the trouble - I might ask that you consider also putting the video on YT and link or embed it from there into your guide.  I'll ask our community leads for their thoughts on an area in our YT channel for instructional stuff like what you are working one.

Either way , please carry on ❤️ !

p.s.  I hope you don't change your mind about the Wireguard or/and VPN docs with good screenshots too. I was  looking forward to reading and trying those myself.

**Comment by j0eybrinkman** [comment]
A.) I checked the articles that I have completed. 
B.) The unchecked ones is what I propose on doing next. 

I definitely still want to create a guide on implementing WireGuard. Although, I consider WireGuard to just be one part of a remote support solution I have implemented for a patron using a Rocky 9 workstation. Since using this solution, I've also experienced the good and the bad of using a P2P VPN vs a centralized VPN for providing end-user remote support. 

Taking all this into account, I'm thinking maybe it would be wise to create a VPN article for WireGuard as well as a centralized VPN (OpenVPN) in the Security category. 

Using x11vnc over SSH for providing remote support over a LAN does not require a VPN, I consider this a good fit for the Desktop category.

Using x11vnc over VPN for providing remote support over a WAN does require a VPN, but the admin still needs to choose the best VPN product for the user, which may make a high-level comparison of using a P2P v centralized VPN for providing remote support to end-users who are away from the org's LAN. 

The only article I removed from my proposed articles is **Using App Images and Maintaining a Secure System with SELinux**. I agree with your comments that they are two separate things, and it is probably the weakest of my proposed articles.

My original vision with this article was a user-oriented education article with a high-level overview of what SELinux is, and how it interacts with app images or binaries installed on the linux system that require elevated privileges similar to working with EXEs and UAC prompts on windows. Basically, my patron was getting some SELinux pop-ups when using Zoom, which was installed via their appimage and it was confusing them. 

The majority of my proposals are stemming from working with a patron in a different geographic location than me who is using a Rocky 9 workstation I flashed for them. I'm up for any guidance or direction regarding and wanted to at least spit ball my thoughts on the proposals and the background of where the ideas for my proposals are coming from.

I did recently start a blog and a YouTube channel. I'd be happy to provide any of footage to the Rocky Documentation project if anyone finds use for it.

youtube.com/@22halomedia

**Comment by wsoyinka** [comment]
Thank you.  

p.s. Cool YT channel :-)

**Comment by j0eybrinkman** [comment]
An exciting update I am glad that I haven't started the Nvidia GPU article yet :) 

https://developer.nvidia.com/blog/nvidia-transitions-fully-towards-open-source-gpu-kernel-modules/#:~:text=With%20the%20R515%20driver%2C%20NVIDIA,GPUs%20in%20an%20alpha%20state.

**Comment by sspencerwire** [comment]
Hey @j0eybrinkman, see if you can think of a shorter title for the x11vnc doc I just merged, to simplify the appearance in the left-hand table of contents. No rush! ... And thanks for your hard work!

**Comment by j0eybrinkman** [comment]
Desktop Sharing via x11vnc+SSH (LAN)

**Comment by j0eybrinkman** [comment]
I tried checking out your light editing commit and adding the new title as well as editing one of the sentences to 'x11vnc, a powerful VNC program, stands out by using the existing X session instead of creating a new one. This feature makes it an excellent tool for remote support, allowing users to control their screen or X session from a distance.' but the pull request had more commits attached than I expected so I closed it.

**Comment by sspencerwire** [comment]
Hello @j0eybrinkman!  I'm just checking in to see how you are coming with your RSOD documents. It's August 2, so we should be to this point:

July 1 - August 30: Content creation and translations.

I'm sending out this message to all of our RSOD docs creators today. :-)

**Comment by j0eybrinkman** [comment]
@sspencerwire, so far, I've created 5 RSOD desktop articles. I still plan on creating the other articles I've listed!

**Comment by wsoyinka** [comment]
@j0eybrinkman  - I believe you've met and surpassed all the criteria for RSOD 2024 .

Thank you ❤️ !!

**Comment by sspencerwire** [comment]
> @sspencerwire, so far, I've created 5 RSOD desktop articles. I still plan on creating the other articles I've listed!

I'm looking forward to your documents! ;-)

**Comment by sspencerwire** [comment]
@j0eybrinkman Thank you for your participation in RSOD, and your on-going involvement in the project! Since the official event is now over, this issue will be closed.
