### ISSUE TITLE
Ezequiel Bruni RSOD proposal

### ISSUE THREAD

**Issue by EzequielBruni** [rocky-linux/documentation#2162]
* RDP server / accessing desktops over RDP - **Complete**
* Firewall app - installation and basic usage **Complete**
* How to integrate ImageApps into your desktop - via ImageApp Pool, which is ironically on Flathub
* How to install essential business software - Zoom, Teams, Slack, Office 365, + a list of alternatives for people who can pick their own tools*  **Complete**
* Flatseal - a basic guide to altering permissions for Flatpak apps
* Dconf Editor - a basic guide to changing Gnome variables visually **Complete**
* Online account integration - a short guide to integrating your online accounts with Gnome. **Complete**
* System Monitor - a basic guide to managing processes in Gnome

\* The installation process is mostly "Have Flathub, go to Software and download the app you want", which is why I'd like to include a short list of alternative options.

**Comment by sspencerwire** [comment]
@wsoyinka and @EzequielBruni these topics look basically OK. A couple of questions for you Ezequiel: 
* The Firewall app: that's a GUI representation, correct?
* Is the "essential business software" entry considered one document?
Thoughts @wsoyinka ?

**Comment by EzequielBruni** [comment]
To answer your questions: Yes and yes.

The purpose of the business software guide is partly to show people how to install that stuff, and partly to let people know what is and isn't available.

Give everyone who's Googling "Rocky Linux Office and Zoom," some answers, you know?

**Comment by wsoyinka** [comment]
Hi - 

I'd like to vote for this list of topics for @EzequielBruni's  entry.  

1. RDP server / accessing desktops over RDP - Complete
2. Firewall app - installation and basic usage
3. How to install essential business software - Zoom, Teams, Slack, Office 365, + a list of alternatives for people who can pick their own tools*
4. Dconf Editor - a basic guide to changing Gnome variables visually
5. Online account integration - a short guide to integrating your online accounts with Gnome.

(Of course, the actual final titles will be tweaked a little for brevity  ) 


Thank you again @EzequielBruni

**Comment by EzequielBruni** [comment]
@wsoyinka @sspencerwire if it works for you, it works for me. And yeah, the titles are only that long for the purposes of the pitch.

**Comment by sspencerwire** [comment]
Hello @EzequielBruni! I'm just checking in to see how you are coming with your RSOD documents. It's August 2, so we *should* be to this point: 

July 1 - August 30: Content creation and translations.

I'm sending out this message to all of our RSOD docs creators today. :-)

**Comment by EzequielBruni** [comment]
@sspencerwire My goal is to have most if not all of the rest of the docs done this week. Been a bit under the weather, but I'm finally ready to dive in.

**Comment by sspencerwire** [comment]
I've marked the Dconf editor option as complete.

**Comment by sspencerwire** [comment]
> I've marked the Dconf editor option as complete.

I've marked the Business apps item as complete as well.

**Comment by EzequielBruni** [comment]
And I've marked the Online Accounts guide as complete. At least it's complete on my end, I think. I would still like to get around to the guide proposals that didn't make the cut for RSOD, but that'll take some time. But my work for RSOD is done! I'm gonna celebrate.

**Comment by sspencerwire** [comment]
@EzequielBruni Thanks for participating in RSOD! Since the event is now over, I will close this issue.
