### ISSUE TITLE
Should Rocky Linux 8 use docker's RHEL folder rather than the CentOS folder?

### ISSUE THREAD

**Issue by jmichaels42** [rocky-linux/documentation#2324]
From here: https://docs.rockylinux.org/gemstones/containers/docker/

The current instructions are to use `sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo`

The ./linux/centos folder appears to be stale: it doesn't have the docker-ce-26.1.4-1.el8.x86_64.rpm package.  The ./linux/rhel folder does have [docker-ce-26.1.4-1.el8.x86_64.rpm](https://download.docker.com/linux/rhel/8/x86_64/stable/Packages/docker-ce-26.1.4-1.el8.x86_64.rpm).

Should the docker dnf repo install for Rocky Linux be changed to this?
`sudo dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo`

**Comment by sspencerwire** [comment]
@NeilHanlon I'm not a Docker guy, what do you think about this suggestion?  If you don't know, perhaps suggest someone who can take a look?  Thanks in advance!

**Comment by NeilHanlon** [comment]
eh, probably can't hurt. CentOS _should_ be fine, but RHEL is technically more correct.

**Comment by sspencerwire** [comment]
@jmichaels42 Thanks very much for your suggestion. I've created a PR dealing with this that will be merged shortly. I'll go ahead and close the issue, but if you need something else, feel free to open a new issue.
