### ISSUE TITLE
fix: revise Valuta

### ISSUE THREAD

**Issue by CBID2** [rocky-linux/documentation#2345]
### Description
According to @gannazhyrnova's conversation on Mattermost, the second sentence in the first line of the Valuta tutorial needs more clarity:

 https://github.com/rocky-linux/documentation/blob/86950468270f8ca6f1d5bcc16d4e1397a45d06ca/docs/desktop/gnome/valuta.md?plain=1#L9
 
### Solution 

Turn `This application quickly converts currencies between two countries.` into `This application quickly converts two currencies.`

**Comment by sspencerwire** [comment]
Fixed with #2349. You can always edit your document and change the wording.
