### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by douglasjpd** [rocky-linux/documentation#2410]
from https://docs.rockylinux.org/labs/systems_administration_I/lab5-networking/#exercise-2

the second paragraph: MACVTAP devices are virtual devices that combine the properties of a softwarei-only interface known as a TAP device as well as the properties of the MACVLAN driver.

"softwarei-only" should be "software-only"

**Comment by sspencerwire** [comment]
Thanks very much for catching this. I'll push a fix.

**Comment by sspencerwire** [comment]
Thanks again @douglasjpd. A push has been merged with this correction.
