### ISSUE TITLE
Create a Guide for Installing a Terminal Emulator on Rocky Linux

### ISSUE THREAD

**Issue by Grammaresque** [rocky-linux/documentation#2417]
*Note: This issue has been addressed using a tool called Terminator. if you use something different, you are invited to submit a Guide for using yours as well. The issue has been assigned 1 time, and can be assigned up to 9 more times.*

Terminal emulators. Rocky Linux comes packaged with GNOME, but everyone has a favorite one that they install wherever they go.

Can you document yours? Why do you use it over something else?

To resolve this issue, create a guide showing how you install and run a particular terminal emulator. Add as a new file, to your fork of the the following directory: docs/desktop/tools. When complete, submit a PR to merge to the main branch of the documentation repository. Then please add that PR# to this issue to make sure they are connected.

For contribution guide visit [README.md](https://github.com/rocky-linux/documentation) for this repository.

Note: Docs are generally created in markdown format and include the following meta information at the top:

---
title: Document title
author: the author of the source (English) version of the document.
contributors: a comma separated list of contributors to the source document.
tested with: a comma separated list of versions, for example 8.6, 9.0
tags:
- desktop
- terminal
- emulator
- whatever 1-word tags are appropriate
---

We believe in you. Progress is better than perfection. This is a team effort and your PR reviewer will assist with details.

**Comment by andcscott** [comment]
Added PR #2439, thanks!

**Comment by Grammaresque** [comment]
Awesome, thank you!

**Comment by andcscott** [comment]
Just FYI that I created #2457 related to this issue. Possibly the last time you'll hear from me for this year's Hacktoberfest, so I just want to give a big **Thank You** to @Grammaresque and the Rocky Linux team for helping us new contributors get started!
