### ISSUE TITLE
iptables enable instruction is incorrect

### ISSUE THREAD

**Issue by jaypricer** [rocky-linux/documentation#246]
In the docs/guides/enabling_iptables_firewall.md I believe the instruction to enable iptables is incorrect:

> Now we need to enable the iptables service to make sure that it starts on boot:
> 
> 'dnf enable iptables'

that the command should be:

> 'systemctl enable iptables'

**Comment by viscountstyx** [comment]
This looks to be fixed already -  ( https://docs.rockylinux.org/guides/enabling_iptables_firewall/ )

> Installing And Enabling iptables Services
> Next we need to install the old iptables services and utilities. This is done with the following:
> 
> dnf install iptables-services iptables-utils
> 
> This will install everything that is needed to run a straight iptables rule set.
> 
> Now we need to enable the iptables service to make sure that it starts on boot:
> 
> systemctl enable iptables

**Comment by viscountstyx** [comment]
Looks to have been merged here: https://github.com/rocky-linux/documentation/pull/248

**Comment by justasojourner** [comment]
Hi both

@sspencerwire and I are building update to the docs website with new navigation and more.

I see this error was fixed after we cloned the branch used to do rebuild. I can update it in the new branch.

**Comment by justasojourner** [comment]
You can check on the test server for the new staging content at this URL

http://18.116.170.184/8.4/guides/security/enabling_iptables_firewall/

**Comment by jaypricer** [comment]
Looks good and +1 for the new Guides navigation organization.  Sorry to have jumped in on this from the outside, was testing out a Rocky VM and going though the guides when I noticed the typo and wasn't sure where to submit it.   Beyond that solid Guides and Books documentation, I really enjoy the tone and style for a novice server admin like myself.

**Comment by hbjydev** [comment]
I'll close it now for you guys
