### ISSUE TITLE
dnf group install is incorrect

### ISSUE THREAD

**Issue by duanfuqiang1128** [rocky-linux/documentation#278]
In the docs/guides/backup/mirroring_lsyncd.md, maybe the dnf install command is incorrect:

> Install Dependencies
> 
>We will need some dependencies: a few that are required by lsyncd itself, and a few that are required to build packages from source. Use this command on your Rocky Linux machine to make sure you have the dependencies you need. If you are going to be building from source, it's a good idea to have all of the development tools installed:
> 
>dnf install groupinstall 'Development Tools'

that the command should be?
> dnf group install 'Development Tools'

**Comment by wsoyinka** [comment]
Hello, 

Thank you for pointing this out !!

We'll update as you have suggested.  But please note that as of the time of this writing `groupinstall` is an acceptable dnf alias .    It is deprecated  and we should probably stop using it , but it works as is. 



```
$ man dnf

.....
Group Command
       Command: group
       Aliases: grp
       Deprecated aliases: groups, grouplist, groupinstall, groupupdate, groupremove, grouperase, groupinfo

```

**Comment by duanfuqiang1128** [comment]
Hello,

Thank you for reply!

I have seen the modification. Thank you for you work. But I found that the translated version was not modified synchronously， so i raised a PR to fix the problem.
