### ISSUE TITLE
Accidental diacritical rendering of backtick chars in navigation pane of Guides link

### ISSUE THREAD

**Issue by NezSez** [rocky-linux/documentation#518]
[https://docs.rockylinux.org/guides/web/mod_SSL_apache/](https://docs.rockylinux.org/guides/web/mod_SSL_apache/)

In the navigation pane (left side)...web...Apache With `mod_ssl`
Windows 10 Firefox (both 96.0.1 and 96.0.2) render what in the md title is `mod_ssl` as if it was diacritics (i.e. accents above the letters); I don't know if the backticks were intentional, should have been single quotes ( ' instead of ` ), accidental or not.

**Comment by sspencerwire** [comment]
@NezSez You could be correct. I think at the time this was merged, mod_ssl was considered the command portion of the title. I'll take a look at the title meta and see. Thanks!

**Comment by NezSez** [comment]
I'd just do a PR, but I'm in the middle of test iterations of some new git/github stuff, working out the nextcloud install steps, and need to work out those details first; sry!

If it was intentional, then there is an issue with the rendering code (backend formatting code, utf glyphs, interaction with browser rendering or fonts, etc), but looks like an easy fix...just git rid of the backticks. It might be worth testing it with Edge, Safari, Chrome, etc if the backticks really should be there.

**Comment by NezSez** [comment]
Issue fixed with Minor change to mod_ssl document #519

**Comment by NezSez** [comment]
NOTE:
I believe this issue was cause by using valid MarkDown to mark `mod_ssl` as "code" which didn't work for html when published.
https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code
