### ISSUE TITLE
script to convert from CentOS or Oracle Linux to Rocky Linux

### ISSUE THREAD

**Issue by shikari7** [rocky-linux/documentation#54]
Can we get a script to convert to Rocky Linux once it's released?  After the CentOS announcement, I ran this script:

https://github.com/oracle/centos2ol

to convert to Oracle Linux but I would much rather be on Rocky Linux than Oracle if possible.   I'm happy to help but I suspect someone else could convert this script to a Rocky version very quickly with the right repo details, etc. 👍

**Comment by hbjydev** [comment]
Moved because it's not a UI/UX issue

**Comment by wsoyinka** [comment]
This is absolutely not a documentation issue either.
