### ISSUE TITLE
Code block formatting

### ISSUE THREAD

**Issue by EzequielBruni** [rocky-linux/documentation#555]
Okay, to continue the discussion from my earlier PR re: code in its own line or paragraph. 

**The Basics**
I'd like to use this:

````markdown
Run this command:

```bash
the-command
```
````
And not:

````markdown
Run this command:

`the-command`
````

****

Now people have been focusing on on whether we should use the syntax-defining feature as shown in the first example. To clear a couple of things up, I'd first like to mention, as others have, there you can do this for a bunch of languages, not just bash.

Secondly, while I see defining the syntax as a big benefit of this formatting method, I *don't* think we should make setting the syntax tags "mandatory" by any means. People can just use a plain code block if it suits them, and I don't want to burden the translators with manually making sure the syntax tags are in there.

Thoughts?

**Comment by EzequielBruni** [comment]
So uh... where did we end up on this?

**Comment by sspencerwire** [comment]
This did not end up anywhere. As far as I'm concerned, using the triple-backticks is fine, and in some ways easier than the single. I did this for the most current PR 586.  I'm going to post this back to ~Documentation and see if we get any additional feedback. I think it is fine, anyway, to suggest that this is the way we go. (I think you were angling for re-writing the contribute document if I'm not mistaken). List it as a recommendation. Frankly, that's what all of our formatting documents are anyway, as the user who writes their own documentation may have other ideas. Posting this to the channel now.

**Comment by EzequielBruni** [comment]
@sspencerwire I wasn't angling for a rewrite of anything as I can recall, TBH. But yeah, I can add this to the formatting doc.
