### ISSUE TITLE
 documentation/docs/guides/custom-linux-kernel.md additional info

### ISSUE THREAD

**Issue by NezSez** [rocky-linux/documentation#602]
@wsoyinka I don't know if you would want to include the following info, or where you'd want to put it if you do, but for RHEL/CentOS/RL et. al. you can see what your installed kernels were config'd with :
`cat /boot/config-<kernel-ver>`
So one could use the following to check the currently running kernel versions' config:
`cat /boot/config-$(uname -r) | grep -i <some-keyword>`
It will show "=m", or "=y" if configured, but doesn't have entries for anything **NOT** configured
(i.e. it will not show "=n")

**Comment by sspencerwire** [comment]
@NezSez You might want to write this up as a gemstone.  It is a simple command that anyone can run on their RHEL clone, Rocky Linux included. It definitely fits that mold. Then if @wsoyinka wants to, he can link to it in his document.

**Comment by wsoyinka** [comment]
Thanks @nezsez !
I think the current guide mentions something about existing config* files
already.  Under kernel configuration section, there's an entry  like:

```
To begin, we’ll copy over and rename the preexisting config file from the
/boot directory into our kernel build environment:

> cp /boot/config-`uname -r` ~/build/kernel/.config

```

And yes, your idea will make for a good standalone gemstone per @
sspencerwire
