### ISSUE TITLE
Nginx proxy_pass not working with SELinux in enforce mode

### ISSUE THREAD

**Issue by romh87** [rocky-linux/documentation#697]
Need to add to documentation a special observation to disable "setenforce 0" 
or better off, "sudo setsebool httpd_can_network_connect 1 -P" , or some better instructions to allow nginx through SELinux

Othewise the nginx proxy_pass capabilities will not work throwing a "502 Bad Gateway" error

**Comment by sspencerwire** [comment]
Hello @romh87 and thank you!  Is this for a particular doc or is it something that would generally apply to Nginx?  If a particular doc or set of documents, let me know which ones, and I'll see about adding and testing those documents. If for a general observation, can you suggest where it would be most appropriate to place this?  Thank you again!

**Comment by romh87** [comment]
Hello @sspencerwire 
It relates to https://github.com/rocky-linux/documentation/pull/698
I can see it was already merged. I will close this issue.
