### ISSUE TITLE
IPA Administration Book

### ISSUE THREAD

**Issue by hbjydev** [rocky-linux/documentation#712]
I'd like to create (or see created) a book on deploying a FreeIPA/IdM installation on Rocky. I'm hoping to make this the first of some "what I learned deploying Rocky in a corporate environment" contributions I want to make. :)

I've got some decent experience working with it so far, and I'd _like_ to contribute, and I should be able to next week.

---

> **Note:** Everywhere "(CLI & UI)" appears, the CLI method is 100% preferred over the UI and will likely be done first.

- [x] Installing IdM
  - [x] From Scratch
  - [ ] With Ansible
- [x] Deploying a master
  - [x] From Scratch
  - [ ] With Ansible
- [ ] Configuring Users
  - [ ] From Scratch (CLI & UI)
  - [ ] With Ansible
- [ ] Configuring Groups
  - [ ] From Scratch (CLI & UI)
  - [ ] With Ansible
- [ ] Configuring HBAC
  - [ ] From Scratch (CLI & UI)
  - [ ] With Ansible
- [ ] Configuring Sudo
  - [ ] From Scratch (CLI & UI)
  - [ ] With Ansible
- [ ] Configuring DNS
  - [ ] From Scratch (CLI & UI)
  - [ ] With Ansible
- [ ] Configuring CA
  - [ ] From Scratch (CLI & UI)
  - [ ] With Ansible
- [ ] Deploying a client
  - [ ] From Scratch
  - [ ] With Ansible
- [ ] Deploying a replica
  - [ ] From Scratch
  - [ ] With Ansible

Some 'maybes':

- [ ] Promoting a new master
- [ ] AD Trust Setup (though this could maybe be its own collection of docs, not just one guide, go over different approaches)
- [ ] Managing replicas (listing, deleting, etc.)
- [ ] Disaster recovery
- [ ] Production checklist (covers things like resources, considerations, networking, backups (or lack thereof, in this case), etc.)

**Comment by sspencerwire** [comment]
@hbjydev I think this would be a great document and a really nice addition to the books section of the documentation. I've got zero experience working with FreeIPA, but could lab test it if the document were started. There's no reason to blast through this though. You can start out with Chapter 1, "Installing IdM" lets say and work through it at your own pace. We can merge it in batches or one Chapter at a time, whichever is your preference. I worked with Antoine on his System Administrator book (and others) and he created a few chapters before we finally merged. He later followed up with some of the later chapters. It works, and makes the process a little less cumbersome for both the creator and the editor. Go for it when you are ready!

**Comment by hbjydev** [comment]
Starting this today on stream :)

**Comment by sspencerwire** [comment]
Sounds good! Thanks @hbjydev !

**Comment by NezSez** [comment]
I will be picking this project up. Sadly I'm traveling a lot until around September, and won't have access to the host I'm using to test the setup with on a regular basis, so I'm going to be a bit slower than usual. Thank you to Wale and Sspencerwire for merging this branch into main so anyone can work on it!

**Comment by NezSez** [comment]
Please see [this branch's IPA dir](https://github.com/rocky-linux/documentation/tree/ipa_wip/docs/books/ipa) if you'd like to help out.

**Comment by sspencerwire** [comment]
There has been no movement on this document for some time. Even though it is conceptually a great idea, it needs a champion to push it forward. At the moment, this has languished for nearly 2 years. If @wsoyinka agrees, and without further input from @hbjydev or @NezSez in the next few days, this issue will be closed along with `ipa_wip` branch. Thanks.

**Comment by sspencerwire** [comment]
Project archived.
